### ISSUE TITLE
golangci-lint not to print line number

### ISSUE THREAD

**Issue by hermitkim1** [cloud-barista/cb-larva#66]
[Proposal]
Update workflow

```yaml
    steps:
    - name: Checkout source code
      uses: actions/checkout@v2
    
    - name: Install golangci-lint
      run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.34.1      
    
    - name: Run golangci-lint
      run: $(go env GOPATH)/bin/golangci-lint run
```
